#baseURL = "https://bullishdesignengineering.github.io/"
baseURL = "bullishdesign.co/" 
languageCode = 'en-us'
title = 'Bullish Design'
theme = 'roxo-muted'

summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Automation"
    url     = "automation"
    weight  = 4
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 5
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 6

# Site Params
[params]
  logo = "images/BD Logo.png"
  logo_footer = "images/BD_Logo-Mini.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  businessName = "Bullish Design"
  description = "Roxo Muted Theme | design agency template by Bullish Design"
  author = "Bullish Design"
  # google analitycs
  googleanalitycsid = "your id"
  # we're using formspree.io for form handling, paste your formspree url below
  #fabform  = "https://fabform.io/f/usag2jl"

  # contact form
  [params.contactform]
    placeholder_first_name        = "Bullish"
    placeholder_last_name         = "Design"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Product Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Code Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/Drafting_Office.jpg"
    heading               = "We’re a Design Studio That Believes In Great Ideas"
    tagline               = "WORK HARD, PLAY HARD"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with Us"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "RECENT WORK"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view project"
    more_works = "MORE WORK"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "LET’S WORK TOGETHER"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Not Convinced"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info"
#address = "713 Elmwood St.<br>Prior Lake, MN 55372"
#phone   = "409-896-1444"
      email   = "BullishDesignEngineering@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About Company"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Medium"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Dribbble"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "We help bring ideas to life:"
        description = "develop concepts<br>iterate designs<br>prototype your imagination<br>realize your dream"
      [params.footer.back_to_top]
        description = "I want to <br> visit again"
